# yaml-language-server: $schema=https://raw.githubusercontent.com/prefix-dev/recipe-format/main/schema.json
package:
  name: cuery
  version: ${{ load_from_file("pyproject.toml").project.version }}

source:
  path: .

build:
  noarch: python
  script:
    - python -m pip install . -vv --no-deps --ignore-installed
  number: ${{ load_from_file("pyproject.toml").tool.rattler.build }}
  skip: ["win"]

requirements:
  host:
    - hatchling
    - pip
    - python 3.11.*
    - setuptools
    - wheel
  run:
    - async-lru
    - aiohttp
    - datamodel-code-generator
    - email-validator
    - fastapi
    - fastapi-mcp
    - glom >=24.11.0
    - google-genai >=1.56.0
    - instructor 1.11.*
    - jsonref
    - jsonschema
    - levenshtein
    - litellm
    - openai >=1.109
    # - xai-sdk
    - pandas <2.3.0
    - pre-commit
    - pyarrow >=12.0.0,<20.0
    - pydantic >=2.0.0
    - python 3.11.*
    - pyyaml
    - rich
    - tiktoken
    - typer
    - uvicorn
    - markdown
    - tldextract
    - python-dotenv
    - tenacity

tests:
  - script:
      - pytest -v -s test
    requirements:
      run:
        - pytest >=7.0.0
        - pytest-asyncio
    files:
      source:
        - test/
about:
  homepage: https://www.graphext.com
  summary: Graphext core types and functions
  description: Other namespace packages will depend on this one.
  documentation: https://docs.graphext.com/
  repository: https://github.com/graphext
